services:
  db:
    container_name: db
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_db_dev
    volumes:
      # - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql # SQL file to initialize the database
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: >
      sh -c "bundle exec rails db:create db:migrate &&
             bundle exec rails s -b 0.0.0.0"

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/src
    environment:
      CHOKIDAR_USEPOLLING: true
    ports:
      - "4200:4200"
    depends_on:
      - backend
    command: npm start

volumes:
  pg_data:
