services:
  db:
    container_name: db
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_db_development
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/src
    environment:
      CHOKIDAR_USEPOLLING: true
    ports:
      - "4200:4200"
    depends_on:
      - backend
    command: npm start

volumes:
  pg_data:
